# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('completion', models.FloatField(blank=True, null=True)),
                ('module_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Aspirant')),
            ],
        ),
    ]
