# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='module_enrolled',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_enrolled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='link.Course'),
            preserve_default=False,
        ),
    ]
