# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
