# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_ngo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
