# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_enrollment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ngo_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='link.NGO'),
            preserve_default=False,
        ),
    ]
