# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_aspirant_skill_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aspirant',
            name='location',
            field=models.CharField(default='Lucknow', max_length=1000),
        ),
        migrations.AddField(
            model_name='locations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Aspirant'),
        ),
    ]
